services:
  nginx:
    image: nginx:alpine
    container_name: nginx-for-static
    ports:
      - "80:80"
    volumes:
      - /var/www:/usr/share/nginx/html:ro
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London  # Adjust to your timezone
      - SERVERPORT=51820   # Port defined in wg0.conf
      - PEERDNS=1.1.1.1    # DNS server for clients
    volumes:
      - /etc/wireguard:/config
    ports:
      - 51820:51820/udp    # Ensure this matches your wg0.conf
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped

  xray:
    image: teddysun/xray:latest
    container_name: xray
    volumes:
      - /etc/xray/config.json:/etc/xray/config.json
      - /etc/xray/log:/var/log/xray
      - /var/cert:/var/cert
    ports:
      - "9090:9090"    # Change to your Xray port
      - "443:443"      # If using TLS, adjust as necessary
    restart: unless-stopped
